"""update_experience_schema_linkedin

Revision ID: a2d59a5a886d
Revises: 99eb0eafcdee
Create Date: 2026-08-09 09:37:37.572257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2d59a5a886d'
down_revision: Union[str, None] = '99eb0eafcdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_media',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_media_experience_id'), 'experience_media', ['experience_id'], unique=False)
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.BIGINT(), nullable=False),
    sa.Column('skill_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    op.add_column('experiences', sa.Column('position_title', sa.String(length=255), nullable=False))
    op.add_column('experiences', sa.Column('organization_name', sa.String(length=255), nullable=False))
    op.add_column('experiences', sa.Column('location_type', sa.String(length=50), nullable=True))
    op.add_column('experiences', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('experiences', sa.Column('start_month', sa.String(length=20), nullable=False))
    op.add_column('experiences', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('experiences', sa.Column('end_month', sa.String(length=20), nullable=True))
    op.add_column('experiences', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('experiences', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.drop_column('experiences', 'category')
    op.drop_column('experiences', 'company_organization')
    op.drop_column('experiences', 'order_index')
    op.drop_column('experiences', 'title')
    op.drop_column('experiences', 'end_date')
    op.drop_column('experiences', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('start_date', sa.DATE(), nullable=False))
    op.add_column('experiences', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('experiences', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('experiences', sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('company_organization', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('experiences', sa.Column('category', mysql.ENUM('work', 'internship', 'freelance', 'research', 'organization', 'other', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('experiences', 'sort_order')
    op.drop_column('experiences', 'end_year')
    op.drop_column('experiences', 'end_month')
    op.drop_column('experiences', 'start_year')
    op.drop_column('experiences', 'start_month')
    op.drop_column('experiences', 'employment_type')
    op.drop_column('experiences', 'location_type')
    op.drop_column('experiences', 'organization_name')
    op.drop_column('experiences', 'position_title')
    op.drop_table('experience_skills')
    op.drop_index(op.f('ix_experience_media_experience_id'), table_name='experience_media')
    op.drop_table('experience_media')
    # ### end Alembic commands ###
